---
- name: Install and configure KVM on RHEL
  hosts: web
  become: yes
  tasks:

    - name: Install necessary KVM packages
      yum:
        name:
          - qemu-kvm
          - libvirt
          - virt-install
          - virt-viewer
          - bridge-utils
          - virt-manager
        state: present

    - name: Ensure libvirtd service is enabled and started
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Reinstall fuse package
      yum:
        name: fuse
        state: latest

 - name: Ensure Cockpit is installed
      yum:
        name: cockpit
        state: present

    - name: Start and enable Cockpit service
      systemd:
        name: cockpit
        state: started
        enabled: yes

    - name: Ensure firewall allows Cockpit
      firewalld:
        service: cockpit
        permanent: yes
        state: enabled

    - name: Reload firewall to apply changes
      firewalld:
        state: reloaded
        permanent: yes
