---
- name: Install and configure KVM on CentOS/RHEL-based systems
  hosts: web
  become: yes
  tasks:

    - name: Install necessary KVM packages
      yum:
        name:
          - qemu-kvm
          - libvirt
          - virt-install
          - bridge-utils
          - virt-manager
        state: present

    - name: Ensure libvirtd service is enabled and started
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Add user to libvirt group
      user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: yes

    - name: Enable IP forwarding (for bridged networking)
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Configure the firewall for KVM
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - libvirt
        - dhcp
        - ssh

    - name: Ensure bridge-utils is installed (for network bridging)
      yum:
        name: bridge-utils
        state: present

    - name: Set up a default network bridge configuration (bridge network)
      copy:
        dest: /etc/sysconfig/network-scripts/ifcfg-br0
        content: |
          TYPE=Bridge
          NAME=br0
          DEVICE=br0
          ONBOOT=yes
          BOOTPROTO=dhcp
          DELAY=0
      notify:
        - Restart network service

  handlers:
    - name: Restart network service
      service:
        name: network
        state: restarted
