---
- name: Install and configure KVM on RHEL
  hosts: web
  become: yes
  tasks:

    - name: Install necessary KVM packages
      yum:
        name:
          - qemu-kvm
          - libvirt
          - virt-install
          - virt-viewer
          - bridge-utils
          - virt-manager
        state: present

    - name: Ensure libvirtd service is enabled and started
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Add user to libvirt group
      user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: yes

    - name: reintalled fuse -y
      yum:
        name: fuse -y
        state: present
