---
- name: Install and configure KVM on RHEL
  hosts: web
  become: yes
  tasks:

    - name: Install necessary KVM packages
      yum:
        name:
          - qemu-kvm
          - libvirt
          - virt-install
          - virt-viewer
          - bridge-utils
          - virt-manager
        state: present

    - name: Ensure libvirtd service is enabled and started
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Reinstall fuse package
      yum:
        name: fuse
        state: latest

         - name: Ensure Cockpit repository is enabled
      yum:
        name: cockpit
        state: present
        enablerepo: "rhel-7-server-extras-rpms" 

    - name: Install Cockpit package
      yum:
        name: cockpit
        state: present

    - name: Enable Cockpit service
      systemd:
        name: cockpit
        enabled: yes
        state: started
