---
- name: This sets up an httpd webserver
  hosts: web
  become: yes
 tasks:
    - name: Ensure the system is up-to-date
      yum:
        name: kvm
        state: latest
        update_cache: yes
    - name: Install KVM packages
      yum:
        name:
          - qemu-kvm
          - libvirt
          - virt-install
          - bridge-utils
          - virt-manager
        state: present
    - name: Ensure libvirt service is enabled and started
      service:
        name: libvirtd
        state: started
        enabled: yes
    - name: Add user to libvirt group (for managing KVM as non-root user)
      user:
        name: "{{ ansible_user }}"
        group: libvirt
        append: yes
    - name: Verify that KVM modules are loaded
      command: lsmod | grep kvm
      register: kvm_modules
      failed_when: kvm_modules.stdout == ""
    - name: Ensure that the network bridge interface is configured
      copy:
        dest: /etc/sysconfig/network-scripts/ifcfg-br0
        content: |
          TYPE=Bridge
          BOOTPROTO=dhcp
          DEVICE=br0
          ONBOOT=yes
          DELAY=0
          NM_CONTROLLED=no
      notify:
        - Restart network service
    - name: Ensure bridged network is configured
      command: nmcli connection add type bridge con-name br0 ifname br0
      ignore_errors: yes
    - name: Start and enable the network service
      service:
        name: network
        state: restarted
        enabled: yes
  handlers:
    - name: Restart network service
      service:
        name: network
        state: restarted
