---
- name: This sets up an httpd webserver
  hosts: web
  become: yes
  tasks:
  - name: Close port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: disabled
  - name: stop http
    service:
      name: httpd 
      state: stopped
  - name: Uninstall apache packages 
    yum:
      name: httpd
      state: absent
  - name: uninstall firewalld package
    yum:
      name: firewalld
      state: absent
